/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef SyntaxTree_CONSTANTS_H
#define SyntaxTree_CONSTANTS_H

#include "SyntaxTree_types.h"

namespace tw { namespace maple { namespace generated {

class SyntaxTreeConstants {
 public:
  SyntaxTreeConstants();

};

extern const SyntaxTreeConstants g_SyntaxTree_constants;

}}} // namespace

#endif
