/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "SyntaxTree_constants.h"

namespace tw { namespace maple { namespace generated {

const SyntaxTreeConstants g_SyntaxTree_constants;

SyntaxTreeConstants::SyntaxTreeConstants() {
  PROTO_VERSION = "0.0.1";

  PROTO_COUNTER = 9LL;

}

}}} // namespace

