//
// D:\test\lib\playerglobal.swc\flash\events\HTTPStatusEvent
//
package flash.events
{
	import flash.events.Event;

	/// @eventType	flash.events.HTTPStatusEvent.HTTP_RESPONSE_STATUS
	[Event(name="httpResponseStatus", type="flash.events.HTTPStatusEvent")] 

	/// @eventType	flash.events.HTTPStatusEvent.HTTP_STATUS
	[Event(name="httpStatus", type="flash.events.HTTPStatusEvent")] 

	public class HTTPStatusEvent extends Event
	{
		/**
		 Unlike the httpStatus event, the httpResponseStatus event is 
	delivered before any response data. Also, the httpResponseStatus event includes 
	values for the responseHeaders and responseURL properties (which are 
	undefined for an httpStatus event. Note that the httpResponseStatus event
	(if any) will be sent before (and in addition to) any complete or error 
	event. 
	
	The HTTPStatusEvent.HTTP_RESPONSE_STATUS constant defines the value of the 
	type property of a httpResponseStatus event object. This event has the following properties:PropertyValuebubblesfalsecancelablefalse; there is no default behavior to cancel.currentTargetThe object that is actively processing the Event 
	object with an event listener.responseURLThe URL from which the response was returned.responseHeadersThe response headers that the response returned, 
	as an array of URLRequestHeader objects.statusThe HTTP status code returned by the server.targetThe network object receiving an HTTP status code.
		 */
		[native(support="none")]
		public static const HTTP_RESPONSE_STATUS : String = "httpResponseStatus";

		/**
		 The HTTPStatusEvent.HTTP_STATUS constant defines the value of the 
	type property of a httpStatus event object. 
	
	This event has the following properties:PropertyValuebubblesfalsecancelablefalse; there is no default behavior to cancel.currentTargetThe object that is actively processing the Event 
	object with an event listener.statusThe HTTP status code returned by the server.targetThe network object receiving an HTTP status code.
		 */
		public static const HTTP_STATUS : String = "httpStatus";

		/// The response headers that the response returned, as an array of URLRequestHeader objects.
		[native(support="none")]
		public function get responseHeaders () : Array;
		[native(support="none")]
		public function set responseHeaders (value:Array) : void;

		/**
		 The URL that the response was returned from. In the case of redirects, this will be different 
	 from the request URL.
		 */
	 [native(support="none")]
		public function get responseURL () : String;
		[native(support="none")]
		public function set responseURL (value:String) : void;

		/**
		 The HTTP status code returned by the server. For example, a value of 404 indicates that the server
	has not found a match for the requested URI. HTTP status codes can be found in sections 10.4 and 10.5
	of the HTTP specification at
	ftp://ftp.isi.edu/in-notes/rfc2616.txt.
	
	If Flash Player or AIR cannot get a status code from the 
	server, or if it cannot communicate with the server, the default value of 0 is passed to your code. 
	A value of 0 can be generated in any player (for example, 
	if a malformed URL is requested), and a value of 0 is always generated by the Flash Player plug-in 
	when it is run in the following browsers, which do not pass HTTP status codes to the player: 
	Netscape, Mozilla, Safari, Opera, and Internet Explorer for the Macintosh.
		 */
		[native(support="none")]
		public function get status () : int;

		public function clone () : Event;

		public function HTTPStatusEvent (type:String, bubbles:Boolean = false, cancelable:Boolean = false, status:int = 0);

		public function toString () : String;
	}
}
